---
defaults: {}

arista-eos:
  platform: eos
  connection_options:
    napalm:
      extras:
        # session_log: 'napalm_nornir_log.log'
cisco-ios:
  platform: cisco_ios
  connection_options:
    netmiko:
      extras:
        secret: 'tacacs-password-here'
        session_log: 'netmiko_nornir_log.log'
cisco-ios-telnet:
  platform: cisco_ios_telnet
  connection_options:
    netmiko:
      extras:
        secret: 'tacacs-password-here'
        session_log: 'netmiko_nornir_log.log'
cisco-nx-os:
  platform: cisco_nxos
  connection_options:
    netmiko:
      extras:
        secret: 'tacacs-password-here'
        session_log: 'netmiko_nornir_log.log'
fortigate:
  platform: fortinet
