---
GNS.CE1:
    hostname: 127.0.0.1
    port: 5003
    # groups:
    #     - IOS

GNS.CE2:
    hostname: 127.0.0.1
    port: 5004
    # groups:
    #     - IOS

GNS.CE3:
    hostname: 127.0.0.1
    port: 5005
    # groups:
    #     - IOS